spring:
  application:
    name: job-hunt-tracker

  datasource:
    url: jdbc:postgresql://localhost:5432/job_hunt_tracker
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: app
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000
  reminder:
    cron: "0 0 9 * * *"